[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython",
    "pybind11",
    # See https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility
    "oldest-supported-numpy",
    "scipy",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
# Build with OpenMP
environment = { MUSPINSIM_WITH_OPENMP=1 }

skip = [
    # Skip building on CPython 3.6 & 3.7 on all platforms as muspinsim requires >= 3.8
    "cp36-*", "cp37-*",
    # The following are disabled due to errors - it seems other libraries
    # ignore these as well
    "pp*",
    "*-win32", "*-manylinux_i686",
    "*-musllinux*"
]

[tool.cibuildwheel.macos]
# Default compiler on macOS doesn't support OpenMP, so install clang
# and force its use through environment variables
before-all = "brew install llvm"
#before-all = "arch -arm64 brew install llvm"
#before-all = "brew reinstall gcc; brew reinstall libomp"

[tool.cibuildwheel.macos.environment]
CC="/usr/local/opt/llvm/bin/clang"
CXX="/usr/local/opt/llvm/bin/clang++"
LDFLAGS="-L/usr/local/opt/llvm/lib"
CPPFLAGS="-I/usr/local/opt/llvm/include"
# CC="/usr/local/bin/gcc-11"
# CXX="/usr/local/bin/g++-11"

[[tool.cibuildwheel.overrides]]
# Disable for macOS ARM builds - currently have various issues with cross-compilation
select = "*macosx_arm64"
environment = { MUSPINSIM_WITH_OPENMP=0 }