[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython",
    "pybind11",
    # See https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility
    "oldest-supported-numpy",
    "scipy",
]
build-backend = "setuptools.build_meta"